# Generated by Django 5.1.7 on 2025-04-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_recommendation_created_at_recommendation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='activite',
            field=models.CharField(default='détente', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='budget',
            field=models.CharField(default='moyen', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='climat',
            field=models.CharField(default='modéré', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='transport',
            field=models.CharField(default='à pied', max_length=50),
        ),
    ]
