# Generated by Django 5.1.7 on 2025-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendation_activite_recommendation_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
